id = "pawn"
name = "Pawn"
version = "0.1.0"
schema_version = 1
authors = ["Fanorisky <fanorisky168@gmail.com>"]
description = "Pawn language support for the Zed Editor, based on the PocketPawn kit."
repository = "https://github.com/Fanorisky/zed-pawn-kit"
snippets = ["./snippets/pawn.json", "./snippets/pawn-completions.json"]

[grammars.pawn]
repository = "https://github.com/Fanorisky/zed-pawn-kit"
rev = "8c5dda9825d7aecd95ab34932a03877795f75113"
path = "grammar"
